apiVersion: v1
kind: Pod
metadata:
  labels:
    app: product-app
  name: product-pod
spec:
  containers:
    - name: product-container
      image: amitpal83/product-service:1.0.1
      volumeMounts:
        - name: product-pod-volume
          mountPath: /app/data
      ports:
        - containerPort: 9080
  volumes:
    - name: product-pod-volume
      emptyDir: {}